CREATE TABLE MA_DETALLES_CONEXION
(
	ID_DETALLE serial primary key ,
    USUARIO VARCHAR(20),
    PASSWORD VARCHAR(10),
    MACS VARCHAR(50),
    TECNOLOGIA_ID INTEGER,
    NOMBRE_VARIABLE VARCHAR(20)
);