CREATE TABLE PARAMETER_SERVICE
(
    ID SERIAL PRIMARY KEY  ,
    USUARIO VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    DEPARTAMENTO VARCHAR(50) NOT NULL,
    MUNICIPIO VARCHAR(50) NOT NULL,
    URL VARCHAR(255) NOT NULL,
    COLABORADOR BOOLEAN NOT null
);